#!/bin/bash -l

SCRIPT_ROOT=$(dirname "$0")
SCRIPT_ROOT=$(cd "$SCRIPT_ROOT" && pwd -P)
if hash pwsh 2>/dev/null; then
    POWERSHELL=pwsh
else
    echo "PowerShell 7+ required."
    exit 1
fi
$POWERSHELL "$SCRIPT_ROOT/axmol.ps1" "$@"
