ax.CONTROL_STATE_NORMAL  = 1
ax.CONTROL_STATE_HIGH_LIGHTED = 2
ax.CONTROL_STATE_DISABLED = 4
ax.CONTROL_STATE_SELECTED = 8

ax.CONTROL_STEPPER_PART_MINUS = 0
ax.CONTROL_STEPPER_PART_PLUS  = 1
ax.CONTROL_STEPPER_PART_NONE  = 2

ax.TABLEVIEW_FILL_TOPDOWN = 0
ax.TABLEVIEW_FILL_BOTTOMUP = 1

ax.SCROLLVIEW_SCRIPT_SCROLL = 0
ax.SCROLLVIEW_SCRIPT_ZOOM   = 1
ax.TABLECELL_TOUCHED        = 2
ax.TABLECELL_HIGH_LIGHT     = 3
ax.TABLECELL_UNHIGH_LIGHT   = 4
ax.TABLECELL_WILL_RECYCLE   = 5
ax.TABLECELL_SIZE_FOR_INDEX = 6
ax.TABLECELL_SIZE_AT_INDEX  = 7
ax.NUMBER_OF_CELLS_IN_TABLEVIEW = 8

ax.SCROLLVIEW_DIRECTION_NONE = -1
ax.SCROLLVIEW_DIRECTION_HORIZONTAL = 0
ax.SCROLLVIEW_DIRECTION_VERTICAL = 1
ax.SCROLLVIEW_DIRECTION_BOTH  = 2

ax.CONTROL_EVENTTYPE_TOUCH_DOWN = 1
ax.CONTROL_EVENTTYPE_DRAG_INSIDE = 2
ax.CONTROL_EVENTTYPE_DRAG_OUTSIDE = 4
ax.CONTROL_EVENTTYPE_DRAG_ENTER = 8
ax.CONTROL_EVENTTYPE_DRAG_EXIT = 16
ax.CONTROL_EVENTTYPE_TOUCH_UP_INSIDE = 32
ax.CONTROL_EVENTTYPE_TOUCH_UP_OUTSIDE = 64
ax.CONTROL_EVENTTYPE_TOUCH_CANCEL    = 128
ax.CONTROL_EVENTTYPE_VALUE_CHANGED   = 256

ax.EDITBOX_INPUT_MODE_ANY = 0
ax.EDITBOX_INPUT_MODE_EMAILADDR = 1
ax.EDITBOX_INPUT_MODE_NUMERIC = 2
ax.EDITBOX_INPUT_MODE_PHONENUMBER = 3
ax.EDITBOX_INPUT_MODE_URL = 4
ax.EDITBOX_INPUT_MODE_DECIMAL = 5
ax.EDITBOX_INPUT_MODE_SINGLELINE = 6

ax.EDITBOX_INPUT_FLAG_PASSWORD = 0
ax.EDITBOX_INPUT_FLAG_SENSITIVE = 1
ax.EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD = 2
ax.EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE = 3
ax.EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS = 4

ax.KEYBOARD_RETURNTYPE_DEFAULT = 0
ax.KEYBOARD_RETURNTYPE_DONE = 1
ax.KEYBOARD_RETURNTYPE_SEND = 2
ax.KEYBOARD_RETURNTYPE_SEARCH = 3
ax.KEYBOARD_RETURNTYPE_GO = 4

ax.ASSETSMANAGER_CREATE_FILE  = 0
ax.ASSETSMANAGER_NETWORK = 1
ax.ASSETSMANAGER_NO_NEW_VERSION = 2
ax.ASSETSMANAGER_UNCOMPRESS     = 3

ax.ASSETSMANAGER_PROTOCOL_PROGRESS =  0
ax.ASSETSMANAGER_PROTOCOL_SUCCESS  =  1
ax.ASSETSMANAGER_PROTOCOL_ERROR    =  2

