using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Axmol.LuaBindings;

internal static class CppEmitter
{
    private static string RegistrationName(GenerationRequest request) =>
        string.IsNullOrWhiteSpace(request.RegistrationName) ? request.Module : request.RegistrationName;

    public static string EmitHeader(GenerationRequest request)
    {
        var registrationName = RegistrationName(request);
        var text = new StringBuilder();
        text.AppendLine("// Generated by Axmol.LuaBindings.Generator. Do not edit.");
        text.AppendLine("#pragma once");
        text.AppendLine("#include \"lua.hpp\"");
        AppendConditionalOpen(text, request);
        text.AppendLine();
        text.AppendLine("namespace ax::lua {");
        text.Append("void register_").Append(registrationName).AppendLine("(lua_State* L);");
        text.AppendLine("} // namespace ax::lua");
        text.AppendLine();
        text.Append("inline int register_all_").Append(registrationName).AppendLine("(lua_State* L)");
        text.AppendLine("{");
        text.Append("    ax::lua::register_").Append(registrationName).AppendLine("(L);");
        text.AppendLine("    return 1;");
        text.AppendLine("}");
        AppendConditionalClose(text, request);
        return text.ToString();
    }

    public static string Emit(GenerationRequest request, IReadOnlyList<BindingClass> classes, IReadOnlyList<BindingEnum> enums)
    {
        var registrationName = RegistrationName(request);
        var text = new StringBuilder();
        text.AppendLine("// Generated by Axmol.LuaBindings.Generator. Do not edit.");
        text.AppendLine("#include \"lua-bindings/runtime/axlua_runtime.h\"");
        text.AppendLine("#include \"lua.hpp\"");
        AppendConditionalOpen(text, request);
        text.AppendLine();

        foreach (var header in request.Headers.Distinct(StringComparer.Ordinal))
        {
            var fullHeader = Path.GetFullPath(Path.Combine(request.RepositoryRoot, header));
            var relativeHeader = Path.GetRelativePath(request.RepositoryRoot, fullHeader).Replace('\\', '/');
            text.Append("#include \"").Append(relativeHeader).AppendLine("\"");
        }

        text.AppendLine();
        text.AppendLine("namespace ax::lua {");
        text.AppendLine();
        text.Append("void register_").Append(registrationName).AppendLine("(lua_State* L)");
        text.AppendLine("{");
        text.Append("    auto module = axlua::Module::from(L, \"")
            .Append(Escape(request.LuaNamespace)).Append("\", \"")
            .Append(Escape(request.LuaTypeNamespace)).AppendLine("\");");

        var classVariables = classes
            .Select((bindingClass, index) => new
            {
                bindingClass.QualifiedName,
                Variable = $"class_{index}_{Sanitize(bindingClass.NativeName)}"
            })
            .ToDictionary(x => x.QualifiedName, x => x.Variable, StringComparer.Ordinal);

        foreach (var bindingClass in classes)
        {
            var variable = classVariables[bindingClass.QualifiedName];
            text.Append("    auto ").Append(variable).Append(" = module.class_<")
                .Append(bindingClass.QualifiedName).Append(">(\"").Append(bindingClass.LuaClassName).AppendLine("\");");
        }

        foreach (var bindingClass in classes)
        {
            var variable = classVariables[bindingClass.QualifiedName];
            var bases = bindingClass.Bases.Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();
            if (bases.Length > 0)
            {
                text.Append("    ").Append(variable).Append(".bases<").AppendJoin(", ", bases).AppendLine(">();");
            }
            if (!bindingClass.IsAbstract && bindingClass.Constructors.Count > 0)
            {
                text.Append("    ").Append(variable).Append(".constructors<");
                var constructorSignatures = bindingClass.Constructors
                    .SelectMany(constructor => ConstructorSignatures(bindingClass.QualifiedName, constructor))
                    .Distinct(StringComparer.Ordinal)
                    .ToArray();
                text.AppendJoin(", ", constructorSignatures);
                text.AppendLine(">();");
            }
            foreach (var methodGroup in bindingClass.Methods.GroupBy(x => x.LuaName, StringComparer.Ordinal))
            {
                var registration = methodGroup.All(x => x.IsStatic) ? "static_method" : "method";
                text.Append("    ").Append(variable).Append('.').Append(registration).Append("(\"")
                    .Append(Escape(methodGroup.Key)).Append("\", ");
                var callables = methodGroup.SelectMany(method => FormatCallables(method, bindingClass)).ToArray();
                if (callables.Length > 1)
                    text.Append("axlua::overload(");
                text.AppendJoin(", ", callables.Select(callable =>
                    callables.Length > 1 ? FormatOverloadCandidate(callable) : callable.Expression));
                if (callables.Length > 1)
                    text.Append(')');
                text.AppendLine(");");
            }
            foreach (var field in bindingClass.Fields)
            {
                text.Append("    ").Append(variable).Append(".field(\"")
                    .Append(Escape(field.LuaName)).Append("\", &")
                    .Append(bindingClass.QualifiedName).Append("::").Append(field.NativeName).AppendLine(");");
            }
        }

        var enumIndex = 0;
        foreach (var bindingEnum in enums)
        {
            var enumVariable = $"enum_{enumIndex++}_{Sanitize(bindingEnum.NativeName)}";
            var owner = bindingEnum.OwnerQualifiedName is not null &&
                        classVariables.TryGetValue(bindingEnum.OwnerQualifiedName, out var ownerVariable)
                ? ownerVariable
                : "module";
            text.Append("    auto ").Append(enumVariable).Append(" = ").Append(owner)
                .Append(".get_or_create_table(\"").Append(Escape(bindingEnum.NativeName)).AppendLine("\");");
            foreach (var value in bindingEnum.Values)
            {
                var literal = value.IsUnsigned && value.UnsignedValue > long.MaxValue
                    ? $"static_cast<lua_Number>({value.UnsignedValue.ToString(System.Globalization.CultureInfo.InvariantCulture)}ull)"
                    : value.IsUnsigned
                        ? value.UnsignedValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "ull"
                        : value.SignedValue.ToString(System.Globalization.CultureInfo.InvariantCulture) + "ll";
                text.Append("    ").Append(enumVariable).Append(".set(\"")
                    .Append(Escape(value.Name)).Append("\", ")
                    .Append(literal)
                    .AppendLine(");");
            }
        }

        text.AppendLine("}");
        text.AppendLine();
        text.AppendLine("} // namespace ax::lua");
        AppendConditionalClose(text, request);
        return text.ToString();
    }

    private static void AppendConditionalOpen(StringBuilder text, GenerationRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.ConditionalExpression))
            text.Append("#if ").AppendLine(request.ConditionalExpression);
    }

    private static void AppendConditionalClose(StringBuilder text, GenerationRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.ConditionalExpression))
            text.AppendLine("#endif");
    }

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        return builder.ToString();
    }

    private static string FormatFunctionPointer(BindingClass bindingClass, BindingMethod method)
    {
        var parameters = string.Join(", ", method.ParameterTypes);
        var returnType = method.ReturnType;
        var type = method.DeclaringType;
        var memberType = method.IsStatic
            ? $"{returnType} (*)({parameters})"
            : $"{returnType} ({type}::*)({parameters}){(method.IsConst ? " const" : string.Empty)}";
        return $"static_cast<{memberType}>(&{type}::{method.NativeName})";
    }

    private static IEnumerable<string> ConstructorSignatures(string type, BindingConstructor constructor)
    {
        var firstDefault = -1;
        for (var index = 0; index < constructor.DefaultValues.Count; index++)
        {
            if (constructor.DefaultValues[index] is not null)
            {
                firstDefault = index;
                break;
            }
        }
        if (firstDefault < 0)
        {
            yield return $"{type}({string.Join(", ", constructor.ParameterTypes)})";
            yield break;
        }

        for (var argumentCount = firstDefault; argumentCount <= constructor.ParameterTypes.Count; argumentCount++)
        {
            if (constructor.DefaultValues.Skip(argumentCount).Any(value => value is null))
                break;
            yield return $"{type}({string.Join(", ", constructor.ParameterTypes.Take(argumentCount))})";
        }
    }

    private sealed record Callable(string Expression, IReadOnlyList<string> ParameterTypes);

    private static string FormatOverloadCandidate(Callable callable)
    {
        return $"axlua::overload_candidate<{string.Join(", ", callable.ParameterTypes)}>({callable.Expression})";
    }

    private static IEnumerable<Callable> FormatCallables(BindingMethod method, BindingClass bindingClass)
    {
        var hasMutableReference = method.ParameterTypes.Any(IsMutableLvalueReference);
        var returnsAxVector = IsAxVectorReturn(method.ReturnType);
        var expression = hasMutableReference
            || returnsAxVector
            ? FormatLambda(method, bindingClass, method.ParameterTypes.Count)
            : FormatFunctionPointer(bindingClass, method);
        yield return new Callable(expression, method.ParameterTypes);

        var firstDefault = -1;
        for (var index = 0; index < method.DefaultValues.Count; index++)
        {
            if (method.DefaultValues[index] is not null)
            {
                firstDefault = index;
                break;
            }
        }
        if (firstDefault < 0)
            yield break;

        for (var argumentCount = firstDefault; argumentCount < method.ParameterTypes.Count; argumentCount++)
        {
            if (method.DefaultValues.Skip(argumentCount).Any(value => value is null))
                break;
            yield return new Callable(FormatLambda(method, bindingClass, argumentCount),
                                      method.ParameterTypes.Take(argumentCount).ToArray());
        }
    }

    private static bool IsMutableLvalueReference(string type)
    {
        var trimmed = type.Trim();
        return trimmed.EndsWith("&", StringComparison.Ordinal) &&
               !trimmed.StartsWith("const ", StringComparison.Ordinal);
    }

    private static bool IsAxVectorReturn(string type)
    {
        var trimmed = type.Trim();
        if (trimmed.StartsWith("const ", StringComparison.Ordinal))
            trimmed = trimmed["const ".Length..].TrimStart();
        while (trimmed.EndsWith("&", StringComparison.Ordinal))
            trimmed = trimmed[..^1].TrimEnd();
        return trimmed.StartsWith("Vector<", StringComparison.Ordinal) ||
               trimmed.StartsWith("ax::Vector<", StringComparison.Ordinal);
    }

    private static string LambdaParameterType(string type)
    {
        if (!IsMutableLvalueReference(type))
            return type;
        return type.Trim()[..^1].TrimEnd();
    }

    private static string FormatLambda(BindingMethod method, BindingClass bindingClass, int argumentCount)
    {
        var parameters = Enumerable.Range(0, argumentCount)
            .Select(index => $"{LambdaParameterType(method.ParameterTypes[index])} arg{index}")
            .ToArray();
        var arguments = Enumerable.Range(0, method.ParameterTypes.Count)
            .Select(index => index < argumentCount ? $"arg{index}" : method.DefaultValues[index]!)
            .ToArray();
        var type = bindingClass.QualifiedName;
        var declaringType = method.DeclaringType;
        var returnsAxVector = IsAxVectorReturn(method.ReturnType);
        var receiver = method.IsStatic
            ? string.Empty
            : $"{(method.IsConst ? "const " : string.Empty)}{type}& self";
        var lambdaParameters = new List<string>();
        if (!string.IsNullOrEmpty(receiver))
            lambdaParameters.Add(receiver);
        lambdaParameters.AddRange(parameters);
        var invocation = method.IsStatic
            ? $"{declaringType}::{method.NativeName}({string.Join(", ", arguments)})"
            : $"static_cast<{(method.IsConst ? "const " : string.Empty)}{declaringType}&>(self).{method.NativeName}({string.Join(", ", arguments)})";
        var body = returnsAxVector
            ? $"return sol::as_table({invocation});"
            : string.Equals(method.ReturnType, "void", StringComparison.Ordinal)
            ? invocation + ";"
            : "return " + invocation + ";";
        var returnType = returnsAxVector ? "auto" : method.ReturnType;
        return $"[]({string.Join(", ", lambdaParameters)}) -> {returnType} {{ {body} }}";
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
