#pragma once

#include "ActionFrame.h"
#include "ActionFrameEasing.h"
#include "ActionManagerEx.h"
#include "ActionNode.h"
#include "ActionObject.h"
#include "Armature.h"
#include "Bone.h"
#include "ArmatureAnimation.h"
#include "ProcessBase.h"
#include "Tween.h"
#include "Datas.h"
#include "BatchNode.h"
#include "DecorativeDisplay.h"
#include "DisplayFactory.h"
#include "DisplayManager.h"
#include "Skin.h"
#include "ColliderDetector.h"
#include "ArmatureDataManager.h"
#include "ArmatureDefine.h"
#include "DataReaderHelper.h"
#include "TransformHelp.h"
#include "ComBase.h"
#include "ComAttribute.h"
#include "ComAudio.h"
#include "ComController.h"
#include "ComRender.h"
#include "InputDelegate.h"
#include "DictionaryHelper.h"
#include "SGUIReader.h"
#include "SSceneReader.h"
#include "TriggerBase.h"
#include "ActionTimeline/ActionTimelineCache.h"
#include "ActionTimeline/Frame.h"
#include "ActionTimeline/TimeLine.h"
#include "ActionTimeline/ActionTimeline.h"
#include "ActionTimeline/ActionTimelineNode.h"
#include "ActionTimeline/BoneNode.h"
#include "ActionTimeline/SkeletonNode.h"
#include "ActionTimeline/CSLoader.h"
#include "CocosStudioExport.h"

namespace cocostudio
{
void CCS_DLL destroyCocosStudio();
}
