if nil == ax.XMLHttpRequest then
    return
end

ax.WEBSOCKET_OPEN     = 0
ax.WEBSOCKET_MESSAGE  = 1
ax.WEBSOCKET_CLOSE    = 2
ax.WEBSOCKET_ERROR    = 3

ax.WEBSOCKET_STATE_CONNECTING = 0
ax.WEBSOCKET_STATE_OPEN       = 1
ax.WEBSOCKET_STATE_CLOSING    = 2
ax.WEBSOCKET_STATE_CLOSED     = 3

ax.XMLHTTPREQUEST_RESPONSE_STRING       = 0
ax.XMLHTTPREQUEST_RESPONSE_ARRAY_BUFFER = 1
ax.XMLHTTPREQUEST_RESPONSE_BLOB         = 2
ax.XMLHTTPREQUEST_RESPONSE_DOCUMENT     = 3
ax.XMLHTTPREQUEST_RESPONSE_JSON         = 4
