// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CSCOMMON_FLATBUFFERS_H_
#define FLATBUFFERS_GENERATED_CSCOMMON_FLATBUFFERS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace flatbuffers {

struct ResourceData;
struct ResourceDataBuilder;

struct ResourceData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResourceDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_PLISTFILE = 6,
    VT_RESOURCETYPE = 8
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  const ::flatbuffers::String *plistFile() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PLISTFILE);
  }
  int32_t resourceType() const {
    return GetField<int32_t>(VT_RESOURCETYPE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyOffset(verifier, VT_PLISTFILE) &&
           verifier.VerifyString(plistFile()) &&
           VerifyField<int32_t>(verifier, VT_RESOURCETYPE, 4) &&
           verifier.EndTable();
  }
};

struct ResourceDataBuilder {
  typedef ResourceData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(ResourceData::VT_PATH, path);
  }
  void add_plistFile(::flatbuffers::Offset<::flatbuffers::String> plistFile) {
    fbb_.AddOffset(ResourceData::VT_PLISTFILE, plistFile);
  }
  void add_resourceType(int32_t resourceType) {
    fbb_.AddElement<int32_t>(ResourceData::VT_RESOURCETYPE, resourceType, 0);
  }
  explicit ResourceDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResourceData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResourceData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResourceData> CreateResourceData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> plistFile = 0,
    int32_t resourceType = 0) {
  ResourceDataBuilder builder_(_fbb);
  builder_.add_resourceType(resourceType);
  builder_.add_plistFile(plistFile);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ResourceData> CreateResourceDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    const char *plistFile = nullptr,
    int32_t resourceType = 0) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  auto plistFile__ = plistFile ? _fbb.CreateString(plistFile) : 0;
  return flatbuffers::CreateResourceData(
      _fbb,
      path__,
      plistFile__,
      resourceType);
}

}  // namespace flatbuffers

#endif  // FLATBUFFERS_GENERATED_CSCOMMON_FLATBUFFERS_H_
