#!/bin/bash -l

AXMOL_CONSOLE_BIN_DIRECTORY=$(dirname "$0")
AXMOL_CONSOLE_BIN_DIRECTORY=$(cd "$AXMOL_CONSOLE_BIN_DIRECTORY" && pwd -P)

if hash pwsh 2>/dev/null; then
    POWERSHELL=pwsh
else
    echo "PowerShell 7+ required."
    exit 1
fi

$POWERSHELL "$AXMOL_CONSOLE_BIN_DIRECTORY/axmol.ps1" "$@"
