#pragma once

#include "CCActionFrame.h"
#include "CCActionFrameEasing.h"
#include "CCActionManagerEx.h"
#include "CCActionNode.h"
#include "CCActionObject.h"
#include "CCArmature.h"
#include "CCBone.h"
#include "CCArmatureAnimation.h"
#include "CCProcessBase.h"
#include "CCTween.h"
#include "CCDatas.h"
#include "CCBatchNode.h"
#include "CCDecorativeDisplay.h"
#include "CCDisplayFactory.h"
#include "CCDisplayManager.h"
#include "CCSkin.h"
#include "CCColliderDetector.h"
#include "CCArmatureDataManager.h"
#include "CCArmatureDefine.h"
#include "CCDataReaderHelper.h"
#include "CCTransformHelp.h"
#include "CCComBase.h"
#include "CCComAttribute.h"
#include "CCComAudio.h"
#include "CCComController.h"
#include "CCComRender.h"
#include "CCInputDelegate.h"
#include "DictionaryHelper.h"
#include "CCSGUIReader.h"
#include "CCSSceneReader.h"
#include "TriggerBase.h"
#include "ActionTimeline/CCActionTimelineCache.h"
#include "ActionTimeline/CCFrame.h"
#include "ActionTimeline/CCTimeLine.h"
#include "ActionTimeline/CCActionTimeline.h"
#include "ActionTimeline/CCActionTimelineNode.h"
#include "ActionTimeline/CCBoneNode.h"
#include "ActionTimeline/CCSkeletonNode.h"
#include "ActionTimeline/CSLoader.h"
#include "CocosStudioExport.h"

namespace cocostudio
{
    void CCS_DLL destroyCocosStudio();
}
