name: check-cstd-headers

on:
  pull_request:
    paths:
      - 'axmol/**'
      - 'extensions/**'
  push:
    branches:
      - dev*
      - release/*
    paths:
      - 'axmol/**'
      - 'extensions/**'
      - 'tests'
      - 'templates'
  workflow_dispatch:

jobs:
  check-cstd-headers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Check for forbidden C++ wrapper C headers
      shell: pwsh
      run: ./tools/cmdline/check-cstd-inc.ps1
